# Generated by Django 5.2.6 on 2025-09-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekartApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Prodects',
            new_name='Products',
        ),
    ]
