# Generated by Django 5.2.6 on 2025-10-06 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartApp', '0004_alter_cart_status_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Product',
            new_name='cart',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order-placed', 'Order-Placed'), ('canceled', 'Canceled'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='order-placed', max_length=50),
        ),
    ]
