# Generated by Django 5.2.6 on 2025-10-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ekartApp', '0005_rename_product_order_cart_alter_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cart',
            new_name='Product',
        ),
    ]
