# Generated by Django 5.2.6 on 2025-10-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartApp', '0007_order_expected_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=1, upload_to='media/category/'),
            preserve_default=False,
        ),
    ]
