# Generated by Django 5.2.6 on 2025-11-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ekartApp', '0008_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
